Economy:
    Money: 5000
    EXP: 500
Module-Names:
    Bank-Menu:
        Name: '&c» &9Bank'
    Back:
        Name: '&b» &aGo Back &b»'
        Lore: '&7Click to return to main menu!'
    Close:
        Name: '&b» &aClose &b»'
        Lore: '&7Click to close the menu!'
    Deposit:
        Name: '&b» &aDeposit &b»'
        Lore: '&7Click to deposit 5000$!'
    Exp-Deposit:
        Name: '&b» &aDeposit EXP &b»'
        Lore: '&7Click to deposit 500 exp(s)!'
    Exp-Withdraw:
        Name: '&b» &aWithdraw EXP &b»'
        Lore: '&7Click to withdraw 500 exp(s)!'
    Information:
        Name: '&b» &aInformation &b»'
        Lore: '&eYour {type}: &7{amount}&r||&eIn Bank: &7{inBank}'
    Splitter:
        Name: '&b» &aBank &b»'
        Lore: '&7The most trustful bank ever!'
    Withdraw:
        Name: '&b» &aWithdraw &b»'
        Lore: '&7Click to withdraw 5000$!'
