Borsa:
    Para: 5000
    Exp: 500
Modül-İsimleri:
    Banka-GUI: '&4Bankam'
    Bilgiler: '&b» &aBilgiler &b»'
    İşlemler: '&b» &aPara Işlemleri &b»'
    Ayırıcı:
        İsim: '&b» &aBanka &b»'
        Lore: '&7En güvenilir banka!'
    Yatır:
        İsim: '&b» &aYatır &b»'
        Lore: '&75000 TL yatırmak için tıkla!'
    Çek:
        İsim: '&b» &aÇek &b»'
        Lore: '&75000 TL Çekmek için tıkla!'
    Çık:
        İsim: '&b» &aKapat &b»'
        Lore: '&7Menüyü kapatmak için tıkla!'
    Geri:
        İsim: '&b» &aGeri Dön &b»'
        Lore: '&7Geri dönmek için tıkla!'
    Tecrübe-Yatır:
        İsim: '&b» &aTecrübe Yatır &b»'
        Lore: '&7500 tecrübe yatırmak için tıkla!'
    Tecrübe-Çek:
        İsim: '&b» &aTecrübe Çek &b»'
        Lore: '&7500 tecrübe çekmek için tıkla!'
# Banka sürümüdür, değiştirmeyin.
Surum: v0.3
Modul-Isımleri:
    Ayirici: '&b» &aBanka &b»'
    Bilgiler: '&b» &aBilgiler &b»'
    Cek: '&b» &aÇek &b»'
    Cik: '&b» &aKapat &b»'
    Geri: '&b» &aGeri Dön &b»'
    Islemler: '&b» &aPara Işlemleri &b»'
    Seviye: '&b» &aSeviye &b»'
    Tecrube-Yatir: '&b» &aTecrübe Yatır &b»'
    Yatir: '&b» &aYatır &b»'
    Bankayi-Ac: '&b» &6Banka: Aç &b»'
    Hesap: '&b» &6Banka: Hesap &b»'
    Sifre: '&b» &6Banka: Şifre &b»'
    Yardim: '&b» &6Banka: Yardım &b»'
# Nelerin sıralamasına bakılıp bakılamayacağını
# buradan ayarlayabilirsiniz.
Sıralama:
    Bakiye: true
    Seviye: true
Economy:
    Money: 5000
    EXP: 500
Module-Names:
    Bank-GUI: '&4My Bank'
    Information: '&b» &aInformation &b»'
    Operations: '&b» &aMoney Operations &b»'
    Splitter:
        Name: '&b» &aBank &b»'
        Lore: '&7The most trustful bank ever!'
    Deposit:
        Name: '&b» &aDeposit &b»'
        Lore: '&7Click to deposit 5000$!'
    Withdraw:
        Name: '&b» &aWithdraw &b»'
        Lore: '&7Click to withdraw 5000$!'
    Close:
        Name: '&b» &aClose &b»'
    Çık:
        Lore: '&7Click to close the menu!'
    Back:
        Name: '&b» &aGo Back &b»'
        Lore: '&7Click to return to main menu!'
    Exp-Deposit:
        Name: '&b» &aDeposit EXP &b»'
        Lore: '&7Click to deposit 500 exp(s)!'
    Exp-Withdraw:
        Name: '&b» &aWithdraw EXP &b»'
        Lore: '&7Click to withdraw 500 exp(s)!'
Version: v1.0
